USE [master]
GO

/****** Object:  Database [KAU_Events_Clubs]    Script Date: 11/12/2023 12:14:24 AM ******/
CREATE DATABASE [KAU_Events_Clubs]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KAU_Events_Clubs', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\KAU_Events_Clubs.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'KAU_Events_Clubs_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\KAU_Events_Clubs_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KAU_Events_Clubs].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [KAU_Events_Clubs] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET ARITHABORT OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [KAU_Events_Clubs] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [KAU_Events_Clubs] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET  DISABLE_BROKER 
GO

ALTER DATABASE [KAU_Events_Clubs] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [KAU_Events_Clubs] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [KAU_Events_Clubs] SET  MULTI_USER 
GO

ALTER DATABASE [KAU_Events_Clubs] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [KAU_Events_Clubs] SET DB_CHAINING OFF 
GO

ALTER DATABASE [KAU_Events_Clubs] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [KAU_Events_Clubs] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [KAU_Events_Clubs] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [KAU_Events_Clubs] SET QUERY_STORE = OFF
GO

ALTER DATABASE [KAU_Events_Clubs] SET  READ_WRITE 
GO

