/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testing;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Abosl
 */
public class insertUpdateDeleteClub extends javax.swing.JFrame {

    /**
     * Creates new form insertClub
     */
    public insertUpdateDeleteClub() {
        initComponents();
        show_clubs();
    }

    
    
    
    
    
    
    
    
    
    public ArrayList<club> clubList(){
        ArrayList<club> clubList = new ArrayList<>();
         try{
 
             
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=KAU_Events_Clubs;user=sa;password=12345";
            Connection con = DriverManager.getConnection(url);
             
             
             
             
            String query1="SELECT * FROM clubBase";
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery(query1);
            club clubO;
            while(rs.next()){
                clubO=new club(rs.getInt("clubCode"), rs.getString("clubName"), rs.getString("clubDescription"), rs.getDate("clubFounded"));
                clubList.add(clubO);
            }
         }
         catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         return clubList;
    }

    
     public void show_clubs(){
        ArrayList<club> list = clubList();
        DefaultTableModel model = (DefaultTableModel)clubTableAUD.getModel();
        Object[] row = new Object[4];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getClubCode();
            row[1]=list.get(i).getClubName();
            row[2]=list.get(i).getClubDescription();
            row[3]=list.get(i).getClubFounded();
     
            model.addRow(row);
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clubID = new javax.swing.JLabel();
        clubName = new javax.swing.JLabel();
        club3 = new javax.swing.JLabel();
        clubCodefield = new javax.swing.JTextField();
        clubNameField = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        AddClub = new javax.swing.JButton();
        clubDate = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        updateClub = new javax.swing.JButton();
        DeleteClubBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        clubTableAUD = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clubID.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        clubID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clubID.setText("Club ID");
        clubID.setAutoscrolls(true);
        clubID.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        clubName.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        clubName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clubName.setText("Club Name");

        club3.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        club3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        club3.setText("Club Description");

        clubCodefield.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        clubCodefield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        clubCodefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubCodefieldActionPerformed(evt);
            }
        });

        clubNameField.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        clubNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        AddClub.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        AddClub.setText("Add");
        AddClub.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        AddClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClubActionPerformed(evt);
            }
        });

        clubDate.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        clubDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clubDate.setText("Club Founded");

        updateClub.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        updateClub.setText("Update");
        updateClub.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        updateClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateClubActionPerformed(evt);
            }
        });

        DeleteClubBtn.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        DeleteClubBtn.setText("Delete");
        DeleteClubBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        DeleteClubBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteClubBtnActionPerformed(evt);
            }
        });

        clubTableAUD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "clubID", "clubName", "clubDescription", "clubFounded"
            }
        ));
        clubTableAUD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clubTableAUDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clubTableAUD);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(AddClub, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(updateClub, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(DeleteClubBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clubID, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(club3)
                            .addComponent(clubName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clubDate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clubNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clubCodefield, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clubID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clubCodefield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clubName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clubNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(club3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clubDate, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddClub)
                    .addComponent(updateClub)
                    .addComponent(DeleteClubBtn))
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClubActionPerformed
       
         try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=KAU_Events_Clubs;user=sa;password=12345";
            Connection con = DriverManager.getConnection(url);
            String query="insert into clubBase (clubCode,clubName,clubDescription,clubFounded)values(?,?,?,?)";
         
           PreparedStatement pst = con.prepareStatement(query);
           String sss=clubCodefield.getText();
           int ss=Integer.parseInt(sss);
           pst.setInt(1, ss);
           pst.setString(2, clubNameField.getText());
           pst.setString(3, jTextField3.getText());
           


java.sql.Date d1 = new java.sql.Date( jDateChooser2.getDate().getTime());
//java.sql.Date d1 ;d1=         (java.sql.Date) jDateChooser2.getDate();
           pst.setDate(4,d1);
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Club inserted successfuly ,   thank you.");
         }
            
         catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
    }//GEN-LAST:event_AddClubActionPerformed

    private void clubCodefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clubCodefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clubCodefieldActionPerformed

    private void updateClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateClubActionPerformed
       try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=KAU_Events_Clubs;user=sa;password=12345";
            Connection con = DriverManager.getConnection(url);
       
       int row= clubTableAUD.getSelectedRow();
            String value=(clubTableAUD.getModel().getValueAt(row, 0).toString());
            String query = "UPDATE clubBase SET clubCode=?, clubName=?,clubDescription=?,clubFounded=? where clubCode="+value;
            
           PreparedStatement pst = con.prepareStatement(query);
           String sss=clubCodefield.getText();
           int ss=Integer.parseInt(sss);
           pst.setInt(1, ss);
           pst.setString(2, clubNameField.getText());
           pst.setString(3, jTextField3.getText());
           java.sql.Date d1 = new java.sql.Date( jDateChooser2.getDate().getTime());
           pst.setDate(4,d1);
           pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)clubTableAUD.getModel();
            model.setRowCount(0);
           show_clubs();
            JOptionPane.showMessageDialog(null, "Updated Sucessfully!");
            
            
            
       
       }
       
       catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
        
    }//GEN-LAST:event_updateClubActionPerformed

    private void DeleteClubBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteClubBtnActionPerformed
      
        
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=KAU_Events_Clubs;user=sa;password=12345";
            Connection con = DriverManager.getConnection(url);
            int row= clubTableAUD.getSelectedRow();
            String value=(clubTableAUD.getModel().getValueAt(row, 0).toString());
            String query="DELETE FROM clubBase where clubCode="+value;
            PreparedStatement pst = con.prepareStatement(query);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)clubTableAUD.getModel();
            model.setRowCount(0);
            show_clubs();
            JOptionPane.showMessageDialog(null,"Deleted Successfully!");
          }
          catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
        
    }//GEN-LAST:event_DeleteClubBtnActionPerformed

    private void clubTableAUDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clubTableAUDMouseClicked
        
        
        
        
        
         int i = clubTableAUD.getSelectedRow();
        TableModel model =clubTableAUD.getModel();
        clubCodefield.setText(model.getValueAt(i,0).toString());
        clubNameField.setText(model.getValueAt(i,1).toString());
        jTextField3.setText(model.getValueAt(i,2).toString());
        jDateChooser2.setDate((Date) model.getValueAt(i,3));
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_clubTableAUDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insertUpdateDeleteClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insertUpdateDeleteClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insertUpdateDeleteClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insertUpdateDeleteClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insertUpdateDeleteClub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddClub;
    private javax.swing.JButton DeleteClubBtn;
    private javax.swing.JLabel club3;
    private javax.swing.JTextField clubCodefield;
    private javax.swing.JLabel clubDate;
    private javax.swing.JLabel clubID;
    private javax.swing.JLabel clubName;
    private javax.swing.JTextField clubNameField;
    private javax.swing.JTable clubTableAUD;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton updateClub;
    // End of variables declaration//GEN-END:variables
}
